spring.application.name=doctorapp

# MongoDB local pour le developpement
spring.mongodb.uri=mongodb://localhost:27017/doctorapp_dev
spring.data.mongodb.auto-index-creation=true

# Logs utiles pour observer les requetes NoSQL executees par l'API
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG

# JWT de dev
app.jwt.secret=dev-secret-key
app.jwt.expiration-ms=3600000
